name: Unzip File and Commit

on: [push]  # Runs the workflow whenever you push to the repo

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Unzip the File
        run: unzip Main.zip -d extracted-files

      - name: Commit Extracted Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add extracted-files
          git commit -m "Extracted files from ZIP"
          git push
